# https://github.com/nicolasbonnici/docker-php8-sf5-nginx-pqsql-boilerplate/tree/develop
# source of inspiration for the docker infrastructure
version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - express-backend
      - svelte-builder
    volumes:
      - ./svelte-frontend/public:/var/www/html/svelte-frontend
      - ./php-backend:/var/www/html/php-backend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx/

  svelte-builder:
    container_name: svelte-builder
    build:
      context: ./svelte-frontend
      dockerfile: Dockerfile
    volumes:
      - ./svelte-frontend:/app
    command: npm run build

  express-backend:
    container_name: express-backend
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - svelte-builder
    links:
      - db
    environment:
      - DATABASE_USER=user
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=demo
      - DATABASE_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    container_name: database
    image: postgres:15-bookworm
    shm_size: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  api_data:
